#!/bin/bash
# This script installs my dotfiles and links them to the repo for easy synchronising. It also installs vundle.
# !!NOTE!! Install RPMfusion Repos first !!NOTE!! #
su -c 'dnf install http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm'

sudo dnf groupinstall 'Development Tools'
sudo dnf groupinstall 'C Development Tools and Libraries'

#My favourite programs and plugins
sudo dnf install vim tmux gnome-tweak-tool steam blender gimp inkscape arduino calibre latexila transmission nemiver mediainfo mediainfo-gui gnome-nettool gnome-font-viewer redshift logisim openscad freecad wireshark glade3 ghex fritzing anki vlc java-openjdk icedtea-web youtube-dl p7zip p7zip-plugins unrar wine yumex-dnf gstreamer-plugins-bad gstreamer-plugins-bad-free-extras gstreamer-plugins-bad-nonfree gstreamer-plugins-ugly gstreamer-ffmpeg gstreamer1-libav gstreamer1-plugins-bad-free-extras gstreamer1-plugins-bad-freeworld gstreamer1-plugins-base-tools gstreamer1-plugins-good-extras gstreamer1-plugins-ugly gstreamer1-plugins-bad-free gstreamer1-plugins-good gstreamer1-plugins-base gstreamer1 kvm virt-manager libvirt libvirt-python

git clone -q https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
#git clone https://github.com/osirase/dotfiles.git ~/gitRepos # I don't think this is needed??

# Creates links to the dotfiles repo
ln -siv ~/gitRepos/dotfiles/vimrc ~/.vimrc
ln -siv ~/gitRepos/dotfiles/tmux.conf ~/.tmux.conf

# Installs Vim Vundle Plugins
vim +PluginInstall +qall

# Enables periodic trim for SSD
systemctl enable fstrim.timer


